import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import ColorSelector from '../src/components/ColorSelector'
import ImageSelector from '../src/components/ImageSelector'
import ProductDetails from '../src/components/ProductDetails'
import useProductDetails from '../src/hooks/useProductDetails'

const Home: NextPage = () => {
  const { product, isLoading, isError } = useProductDetails();
  if (isLoading) {
    return <>{"Loading..."}</>
  }

  if (isError) {
    console.log(isError)
    return <>{"Whoops..."}</>
  }

  return (
    <div>
      <Head>
        <title>Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-lg flex flex-row px-4 mx-auto" style={{width: '1024px'}}>
        <section className="w-4/12 p-4">
          <ImageSelector
            title={product?.title}
            images={[product.image]}
          />
        </section>
        <section className="w-8/2 p-4">
          <ProductDetails product={product}/>
          <ColorSelector product={product}/>
        </section>
        
      </main>
    </div>
  )
}

export default Home
